### ISSUE TITLE
White page on other component > Alledia framework fix solved it

### ISSUE THREAD

**Issue by Ruud68** [OSTraining/AllediaFramework#10]
Hi,
was running into a white page situation with the advanced poll component from extstore.
The developer had a look into it and found that the culprit was in the alledia framework.

( ! ) Fatal error: Call to a member function xpath() on a non-object in libraries\allediaframework\Framework\Joomla\Extension\Generic.php on line 457

He was kind enough to fix that for me, so want to share this with you so you can have a look at it and 'adopt' the change is you feel okay about it :)

it is in file: ./libraries/allediaframework/Framework/Joomla/Extension/Generic.php
replace:
                        $footerElement = $manifest->xpath('//field[@type="customfooter"]');

with:
 			if ($manifest) {
 				$footerElement = $manifest->xpath('//field[@type="customfooter"]');
 			}

Hope this helps!

**Comment by Ruud68** [comment]
anyone?

**Comment by andergmartins** [comment]
Hi @Ruud68,

Sorry, I missed both messages. I will take a look on it asap.

Thanks for sharing this!

**Comment by Ruud68** [comment]
Hope it helps :) Keep up the good work!

**Comment by andergmartins** [comment]
Thanks @Ruud68
