### ISSUE TITLE
Update Warnings in Alledia Framework 1.3.0

### ISSUE THREAD

**Issue by photodude** [OSTraining/AllediaFramework#9]
The following "warnings" display on checking for updates in Joomla 3.4.1 and Alledia Framework 1.3.0
```
Update: Could not open update site #19 "Alledia Framework", URL: https://deploy.ostraining.com/client/update/free/stable/lib_allediaframework/extension.xml
```

**Comment by htmgarcia** [comment]
Hi @photodude 
Please try the suggestion from https://github.com/OSTraining/OSSystem/issues/4

**Comment by photodude** [comment]
@htmgarcia This issue seems to have resolved itself. Last check for updates did not return  the warning about not being able to open the update site.

related issues are all ready posted in the forum
https://www.alledia.com/forum/osmap/162/
https://www.alledia.com/forum/osmap/146/

Closing as this appears to be resolved
